version: '3.8'

services:
  api:
    build:
      context: ./pragmabrewery
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - pragmanet
  dashboard:
    build:
      context: ./pragmabrewery-dashboard
      dockerfile: Dockerfile
    ports:
      - 8000:80
    networks:
      - pragmanet

networks:
  pragmanet:
    name: pragmanet

volumes:
  demodb: {}
